---
# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
{{- if .Values.os2mo_smtp.enabled }}
{{- if or (not .Values.os2mo_smtp.database.name) (not .Values.os2mo_smtp.database.user) }}
  {{- fail "Must have os2mo_smtp.database.name and os2mo_smtp.database.user set" }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: os2mo-smtp
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os2mo-smtp
  template:
    metadata:
      labels:
        app: os2mo-smtp
    spec:
      containers:
        - name: os2mo-smtp
          image: "{{ .Values.os2mo_smtp.image.registry }}/{{ .Values.os2mo_smtp.image.repository }}:{{ .Values.os2mo_smtp.image.tag }}"
          env:
            - name: FASTRAMQPI__MO_URL
              value: "http://mo-service:5000"
            - name: FASTRAMQPI__CLIENT_ID
              value: "dipex"
            - name: FASTRAMQPI__AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: FASTRAMQPI__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            {{ if .Values.amqp.enabled }}
            - name: FASTRAMQPI__AMQP__URL
              valueFrom:
                secretKeyRef:
                  name: amqp-url-secret
                  key: url
            {{ end }}
            {{ toYaml .Values.os2mo_smtp.extraEnv | indent 12 | trim }}
              # Database
            - name: FASTRAMQPI__DATABASE__USER
              value: {{ .Values.os2mo_smtp.database.user }}
            - name: FASTRAMQPI__DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os2mo-smtp-database-secret
                  key: database_password
            - name: FASTRAMQPI__DATABASE__HOST
              value: {{ .Values.database.host }}
            - name: FASTRAMQPI__DATABASE__NAME
              value: {{ .Values.os2mo_smtp.database.name }}
          resources:
            {{- toYaml .Values.os2mo_smtp.resources | nindent 12 }}
      initContainers:
        - name: os2mo-smtp-db-init
          image: "{{ .Values.os2mo_smtp.database.init.image.registry }}/{{ .Values.os2mo_smtp.database.init.image.repository }}:{{ .Values.os2mo_smtp.database.init.image.tag }}"
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.database.host }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{ if .Values.database.password_secret }}
                  name: {{ .Values.database.password_secret }}
                  {{ else }}
                  name: mox-db-secret
                  {{ end }}
                  key: db_password
            # The ENVs below are named KEYCLOAK_... since we are currently using
            # the Keycloak DB init-container. This will be fixed in
            # https://redmine.magenta-aps.dk/issues/57967
            - name: KEYCLOAK_DB_NAME
              value: {{ .Values.os2mo_smtp.database.name }}
            - name: KEYCLOAK_DB_USER
              value: {{ .Values.os2mo_smtp.database.user }}
            - name: KEYCLOAK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os2mo-smtp-database-secret
                  key: database_password
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
{{- end }}
